#!/bin/bash

# Don't use set -e when script is sourced - it exits the shell on errors

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${GREEN}[*]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running with -i flag (install mode)
INSTALL_MODE=false
while getopts "i" opt; do
    case $opt in
        i) INSTALL_MODE=true ;;
        *) ;;
    esac
done

if [ "$INSTALL_MODE" = false ]; then
    echo "Usage: . ./scarcepay-setup.sh -i"
    echo ""
    echo "Required environment variables:"
    echo "  SCARCEPAY_HOST     - Your domain (e.g., pay.example.com)"
    echo ""
    echo "Optional environment variables:"
    echo "  POSTGRES_PASSWORD  - Database password (default: auto-generated)"
    return 0 2>/dev/null || exit 0
fi

echo ""
echo "============================================"
echo "        ScarcePay Setup Script"
echo "============================================"
echo ""

# Check required environment variables
if [ -z "$SCARCEPAY_HOST" ]; then
    print_error "SCARCEPAY_HOST environment variable is required"
    echo ""
    echo "Example:"
    echo "  export SCARCEPAY_HOST=\"pay.example.com\""
    echo "  . ./scarcepay-setup.sh -i"
    return 1 2>/dev/null || exit 1
fi

# Check for Docker
print_status "Checking for Docker..."
if ! command -v docker &> /dev/null; then
    print_error "Docker is not installed"
    echo "Please install Docker: https://docs.docker.com/get-docker/"
    return 1 2>/dev/null || exit 1
fi
print_status "Docker found: $(docker --version)"

# Check for Docker Compose
print_status "Checking for Docker Compose..."
if ! docker compose version &> /dev/null; then
    print_error "Docker Compose is not installed or not available"
    echo "Please install Docker Compose: https://docs.docker.com/compose/install/"
    return 1 2>/dev/null || exit 1
fi
print_status "Docker Compose found: $(docker compose version --short)"

# Generate password if not provided
if [ -z "$POSTGRES_PASSWORD" ]; then
    POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | cut -c1-32)
    print_status "Generated random PostgreSQL password"
fi

# Create .env file
print_status "Creating .env file..."
cat > .env << EOF
# ScarcePay Configuration
# Generated by scarcepay-setup.sh on $(date)

# Domain for your ScarcePay instance
SCARCEPAY_HOST=${SCARCEPAY_HOST}

# PostgreSQL credentials
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=scarcepay

# Database URL for the API
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/scarcepay

# NEAR Intents API Key (required for payment processing)
# Get your key at: https://1click.chaindefuser.com
NEAR_INTENTS_API_KEY=
EOF

print_status ".env file created"

# Update Caddyfile with the host
print_status "Configuring Caddyfile for ${SCARCEPAY_HOST}..."
cat > Caddyfile << EOF
${SCARCEPAY_HOST} {
	handle /api/* {
		reverse_proxy api:3001
	}

	handle {
		reverse_proxy web:3000
	}
}
EOF

print_status "Caddyfile configured"

# docker-compose.yml is already configured in the repo with proper targets
print_status "Using existing docker-compose.yml configuration"

# Build and start services
print_status "Building Docker images..."
if ! docker compose build; then
    print_error "Docker build failed. Check the output above for details."
    echo ""
    echo "Common issues:"
    echo "  - Missing Dockerfile"
    echo "  - Syntax errors in Dockerfile"
    echo "  - Network issues pulling base images"
    return 1 2>/dev/null || exit 1
fi

print_status "Starting ScarcePay..."
if ! docker compose up -d; then
    print_error "Failed to start services. Check logs with: docker compose logs"
    return 1 2>/dev/null || exit 1
fi

echo ""
echo "============================================"
echo "        ScarcePay Setup Complete!"
echo "============================================"
echo ""
echo "Your ScarcePay instance is now running at:"
echo ""
echo "  https://${SCARCEPAY_HOST}"
echo ""
echo "Next steps:"
echo "  1. Point your DNS A record for ${SCARCEPAY_HOST} to this server"
echo "  2. Add your NEAR Intents API key to .env file"
echo "  3. Run 'docker compose restart api' after updating .env"
echo ""
echo "Useful commands:"
echo "  docker compose logs -f      # View logs"
echo "  docker compose down         # Stop services"
echo "  docker compose up -d        # Start services"
echo ""
